language: python

services:
  - rabbitmq

python:
  - '3.4'
  - '3.5'
  - '3.6'

install:
  - pip install -U pip setuptools
  - pip install -U -e ".[dev]"

script:
  - make test

deploy:
  - provider: pypi
    on:
      tags: true
      repo: nameko/nameko-tracer
      condition: $TRAVIS_PYTHON_VERSION = "3.5"
    distributions: sdist bdist_wheel
    user: iky
    password:
      secure: YZTpLt7/zukqFiSUBnLGGeNkcd9WYg936BrGjeNRdMZe2idZHVyHFgTGmL9regEyWUrDvb2ju3ND/Hw0heH0QfsOJqf4J6SPEXPmcmjog262xjZI3tj0mzQglIBPpS+VUn+elmfz3JkzlDasn4PVOSkx3U9+vQ3unwzngJmqi5dGkzycOba0CvzA2iYSinft9PCZny3wjwRgu3B3zXZ0remHuScwpDar4DbybYdAzp8mREirojO9wHObC5ltPsbLUKwQu0JtlL98lN6pXOYfVwLAuPdcplUJG6IGuoNLht+OGRVrUQnwA6MT+Ku6TJEQnR+tvUpBJdnmAeeka+3L/s/XRT/cqn4//OD0rFn3+6nnc9oh7Nm7Z8KYJkLriP5j9gxnV6Qyh3TmE5rgnOIoqXLbCBlFp0NAmaLddmxIugV8IF1sqA9f1mAvSkFyzr2gSM5UqbR3/v7i4yjM6uTDcLjx/IWdkivGekGf878QskusCe81rurXzcSD5bQYecf3mT+Z6unl4HOZ+HmYlbWo+VtIV6nfK4kz54e8NODkgVwd4K2fLRAW1rw8qQnpVcQ5qLb7XioTYV5SODCZkwl/v4WsNcpHXxet3uzRtrXVkLeiifLcXwUSH6WTOShmotwv3DNeIFYnl2T4oKDA4jbP/KusgtAwHoi9z6VcM36u5Uc=
